name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: gnyman/golangci-lint-action@check-patch-for-go-on-new
        with:
          only-new-issues: true
